details:
    page_title: Kiosk DataBoard
layout:
    - row_1_of_2:
        - col_1_of_2:
            - tile_template: listing
              tile_id: list_connected_users
              title: Users Connected
              classes:

        - col_1_of_2:
            - tile_template: big_value
              tile_id: nbr_test
              title: Tests
              classes:

    - row_1_of_2:
        - col_1_of_2:
            - tile_template: norm_chart
              tile_id: SSL_errors
              title: SSL Errors
              classes:

        - col_1_of_2:
            - tile_template: norm_chart
              tile_id: Crashes
              title: Crash
              classes: