details:
    page_title: Tous les entrepôts
layout:
    - row_1_of_2:
        - col_1_of_2 flip-time-6:
            - tile_template: big_value
              tile_id: bv_wh_bydevices
              title: Nombre de terminaux
              classes:

            - tile_template: just_value
              tile_id: jv_whs_scans
              title: Nombre de scans Total
              classes:

        - col_1_of_2:
            - tile_template: half_doughnut_chart
              tile_id: hd_online_wh
              title: Terminaux OnLine / Offline
              classes:

        - col_1_of_2:
            - tile_template: half_doughnut_chart
              tile_id: hd_wh_device_used
              title: Nombre de Terminal Utilisé
              classes:

    - row_1_of_2:
        - col_1_of_2:
            - tile_template: big_value
              tile_id: bv_wh
              title: Terminaux  
              classes:

        - col_1_of_2:
            - tile_template: big_value
              tile_id: bv_wh_network
              title: Répartition des terminaux
              classes:
                -
        - col_1_of_2:
            - tile_template: big_value
              tile_id: bv_wh_used
              title: Répartition des Terminaux
              classes:

