details:
  page_title: Entrepôt N°098 - Chalons
layout:
  - row_1_of_2:
      - col_1_of_2 flip-time-6:
          - tile_template: big_value
            tile_id: bv_wh_bydevices_098
            title: Nombre de terminaux
            classes:

          - tile_template: just_value
            tile_id: jv_whs_scans_098
            title: Nombre de scans Total
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_wh_098
            title: Chalons 098 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_wh_device_used_098
            title: Chalons 098 - Nombre de Terminal Utilisé
            classes:

  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_098
            title: Terminaux Chalons 098
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_network_098
            title: Chalons 098 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_used_098
            title: Chalons 098 - Répartition des Terminaux
            classes:
