details:
  page_title: Entrepôt N°433 - Libercourt
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_bydevices_433
            title: Nombre de terminaux
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_wh_433
            title: Libercourt 433 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_wh_device_used_433
            title: Libercourt 433 - Nombre de Terminal Utilisé
            classes:

  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_433
            title: Terminaux Libercourt 433
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_network_433
            title: Libercourt 433 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_used_433
            title: Libercourt 433 - Répartition des Terminaux
            classes:
