details:
  page_title: Entrepôt N°443 - Saint Leger
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_bydevices_443
            title: Nombre de terminaux
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_wh_443
            title: Saint Leger 443 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_wh_device_used_443
            title: Saint Leger 443 - Nombre de Terminal Utilisé
            classes:

  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_443
            title: Terminaux Saint Leger 443
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_network_443
            title: Saint Leger 443 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_used_443
            title: Saint Leger 443 - Répartition des Terminaux
            classes:
