details:
  page_title: Entrepôt N°450 - Dourges 2
layout:
  - row_1_of_2:
      - col_1_of_2 flip-time-6:
          - tile_template: big_value
            tile_id: bv_wh_bydevices_450
            title: Nombre de terminaux
            classes:

          - tile_template: just_value
            tile_id: jv_whs_scans_450
            title: Nombre de scans Total
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_wh_450
            title: Dourges 2 450 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_wh_device_used_450
            title: Dourges 2 450 - Nombre de Terminal Utilisé
            classes:

  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_450
            title: Terminaux Dourges 2 450
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_network_450
            title: Dourges 2 450 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_used_450
            title: Dourges 2 450 - Répartition des Terminaux
            classes:
