details:
  page_title: Magasin N°003 - Merlimont
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_003
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_003
            title: Merlimont 003 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_003
            title: Merlimont 003 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_003
            title: Terminaux Merlimont 003
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_003
            title: Merlimont 003 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_003
            title: Merlimont 003 - Répartition des Terminaux
            classes:

