details:
  page_title: Magasin N°004 - Longueau
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_004
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_004
            title: Longueau 004 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_004
            title: Longueau 004 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_004
            title: Terminaux Longueau 004
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_004
            title: Longueau 004 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_004
            title: Longueau 004 - Répartition des Terminaux
            classes:

