details:
  page_title: Magasin N°005 - Rennes sud
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_005
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_005
            title: Rennes sud 005 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_005
            title: Rennes sud 005 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_005
            title: Terminaux Rennes sud 005
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_005
            title: Rennes sud 005 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_005
            title: Rennes sud 005 - Répartition des Terminaux
            classes:

