details:
  page_title: Magasin N°006 - Nice
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_006
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_006
            title: Nice 006 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_006
            title: Nice 006 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_006
            title: Terminaux Nice 006
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_006
            title: Nice 006 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_006
            title: Nice 006 - Répartition des Terminaux
            classes:

