details:
  page_title: Magasin N°010 - Montsoult
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_010
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_010
            title: Montsoult 010 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_010
            title: Montsoult 010 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_010
            title: Terminaux Montsoult 010
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_010
            title: Montsoult 010 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_010
            title: Montsoult 010 - Répartition des Terminaux
            classes:

