details:
  page_title: Magasin N°011 - Villeneuve d'ascq
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_011
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_011
            title: Villeneuve d'ascq 011 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_011
            title: Villeneuve d'ascq 011 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_011
            title: Terminaux Villeneuve d'ascq 011
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_011
            title: Villeneuve d'ascq 011 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_011
            title: Villeneuve d'ascq 011 - Répartition des Terminaux
            classes:

