details:
  page_title: Magasin N°012 - Lens
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_012
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_012
            title: Lens 012 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_012
            title: Lens 012 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_012
            title: Terminaux Lens 012
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_012
            title: Lens 012 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_012
            title: Lens 012 - Répartition des Terminaux
            classes:

