details:
  page_title: Magasin N°013 - Montigny
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_013
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_013
            title: Montigny 013 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_013
            title: Montigny 013 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_013
            title: Terminaux Montigny 013
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_013
            title: Montigny 013 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_013
            title: Montigny 013 - Répartition des Terminaux
            classes:

