details:
  page_title: Magasin N°014 - Valenciennes
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_014
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_014
            title: Valenciennes 014 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_014
            title: Valenciennes 014 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_014
            title: Terminaux Valenciennes 014
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_014
            title: Valenciennes 014 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_014
            title: Valenciennes 014 - Répartition des Terminaux
            classes:

