details:
  page_title: Magasin N°015 - Montpellier
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_015
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_015
            title: Montpellier 015 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_015
            title: Montpellier 015 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_015
            title: Terminaux Montpellier 015
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_015
            title: Montpellier 015 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_015
            title: Montpellier 015 - Répartition des Terminaux
            classes:

