details:
  page_title: Magasin N°018 - Dijon
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_018
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_018
            title: Dijon 018 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_018
            title: Dijon 018 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_018
            title: Terminaux Dijon 018
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_018
            title: Dijon 018 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_018
            title: Dijon 018 - Répartition des Terminaux
            classes:

