details:
  page_title: Magasin N°019 - Bourges
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_019
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_019
            title: Bourges 019 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_019
            title: Bourges 019 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_019
            title: Terminaux Bourges 019
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_019
            title: Bourges 019 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_019
            title: Bourges 019 - Répartition des Terminaux
            classes:

