details:
  page_title: Magasin N°021 - Vitry-sur-seine
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_021
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_021
            title: Vitry-sur-seine 021 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_021
            title: Vitry-sur-seine 021 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_021
            title: Terminaux Vitry-sur-seine 021
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_021
            title: Vitry-sur-seine 021 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_021
            title: Vitry-sur-seine 021 - Répartition des Terminaux
            classes:

