details:
  page_title: Magasin N°022 - Bonneuil
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_022
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_022
            title: Bonneuil 022 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_022
            title: Bonneuil 022 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_022
            title: Terminaux Bonneuil 022
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_022
            title: Bonneuil 022 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_022
            title: Bonneuil 022 - Répartition des Terminaux
            classes:

