details:
  page_title: Magasin N°024 - Ste genevieve des bois
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_024
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_024
            title: Ste genevieve des bois 024 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_024
            title: Ste genevieve des bois 024 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_024
            title: Terminaux Ste genevieve des bois 024
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_024
            title: Ste genevieve des bois 024 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_024
            title: Ste genevieve des bois 024 - Répartition des Terminaux
            classes:

