details:
  page_title: Magasin N°025 - Tours sud
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_025
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_025
            title: Tours sud 025 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_025
            title: Tours sud 025 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_025
            title: Terminaux Tours sud 025
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_025
            title: Tours sud 025 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_025
            title: Tours sud 025 - Répartition des Terminaux
            classes:

