details:
  page_title: Magasin N°026 - Lyon
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_026
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_026
            title: Lyon 026 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_026
            title: Lyon 026 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_026
            title: Terminaux Lyon 026
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_026
            title: Lyon 026 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_026
            title: Lyon 026 - Répartition des Terminaux
            classes:

