details:
  page_title: Magasin N°028 - Le mans
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_028
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_028
            title: Le mans 028 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_028
            title: Le mans 028 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_028
            title: Terminaux Le mans 028
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_028
            title: Le mans 028 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_028
            title: Le mans 028 - Répartition des Terminaux
            classes:

