details:
  page_title: Magasin N°029 - Chelles
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_029
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_029
            title: Chelles 029 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_029
            title: Chelles 029 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_029
            title: Terminaux Chelles 029
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_029
            title: Chelles 029 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_029
            title: Chelles 029 - Répartition des Terminaux
            classes:

