details:
  page_title: Magasin N°030 - Dunkerque
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_030
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_030
            title: Dunkerque 030 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_030
            title: Dunkerque 030 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_030
            title: Terminaux Dunkerque 030
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_030
            title: Dunkerque 030 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_030
            title: Dunkerque 030 - Répartition des Terminaux
            classes:

