details:
  page_title: Magasin N°032 - Lesquin
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_032
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_032
            title: Lesquin 032 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_032
            title: Lesquin 032 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_032
            title: Terminaux Lesquin 032
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_032
            title: Lesquin 032 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_032
            title: Lesquin 032 - Répartition des Terminaux
            classes:

