details:
  page_title: Magasin N°034 - Tourcoing
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_034
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_034
            title: Tourcoing 034 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_034
            title: Tourcoing 034 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_034
            title: Terminaux Tourcoing 034
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_034
            title: Tourcoing 034 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_034
            title: Tourcoing 034 - Répartition des Terminaux
            classes:

