details:
  page_title: Magasin N°036 - Chartres
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_036
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_036
            title: Chartres 036 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_036
            title: Chartres 036 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_036
            title: Terminaux Chartres 036
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_036
            title: Chartres 036 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_036
            title: Chartres 036 - Répartition des Terminaux
            classes:

