details:
  page_title: Magasin N°037 - Bordeaux Lac
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_037
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_037
            title: Bordeaux Lac 037 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_037
            title: Bordeaux Lac 037 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_037
            title: Terminaux Bordeaux Lac 037
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_037
            title: Bordeaux Lac 037 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_037
            title: Bordeaux Lac 037 - Répartition des Terminaux
            classes:

