details:
  page_title: Magasin N°039 - Charleville-mezieres
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_039
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_039
            title: Charleville-mezieres 039 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_039
            title: Charleville-mezieres 039 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_039
            title: Terminaux Charleville-mezieres 039
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_039
            title: Charleville-mezieres 039 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_039
            title: Charleville-mezieres 039 - Répartition des Terminaux
            classes:

