details:
  page_title: Magasin N°040 - Strasbourg
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_040
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_040
            title: Strasbourg 040 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_040
            title: Strasbourg 040 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_040
            title: Terminaux Strasbourg 040
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_040
            title: Strasbourg 040 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_040
            title: Strasbourg 040 - Répartition des Terminaux
            classes:

