details:
  page_title: Magasin N°043 - Boulogne
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_043
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_043
            title: Boulogne 043 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_043
            title: Boulogne 043 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_043
            title: Terminaux Boulogne 043
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_043
            title: Boulogne 043 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_043
            title: Boulogne 043 - Répartition des Terminaux
            classes:

