details:
  page_title: Magasin N°046 - Saint Brieuc
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_046
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_046
            title: Saint Brieuc 046 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_046
            title: Saint Brieuc 046 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_046
            title: Terminaux Saint Brieuc 046
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_046
            title: Saint Brieuc 046 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_046
            title: Saint Brieuc 046 - Répartition des Terminaux
            classes:

