details:
  page_title: Magasin N°047 - Toulon
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_047
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_047
            title: Toulon 047 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_047
            title: Toulon 047 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_047
            title: Terminaux Toulon 047
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_047
            title: Toulon 047 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_047
            title: Toulon 047 - Répartition des Terminaux
            classes:

