details:
  page_title: Magasin N°048 - Arras
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_048
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_048
            title: Arras 048 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_048
            title: Arras 048 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_048
            title: Terminaux Arras 048
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_048
            title: Arras 048 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_048
            title: Arras 048 - Répartition des Terminaux
            classes:

