details:
  page_title: Magasin N°049 - Merignac
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_049
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_049
            title: Merignac 049 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_049
            title: Merignac 049 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_049
            title: Terminaux Merignac 049
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_049
            title: Merignac 049 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_049
            title: Merignac 049 - Répartition des Terminaux
            classes:

