details:
  page_title: Magasin N°050 - Maubeuge
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_050
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_050
            title: Maubeuge 050 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_050
            title: Maubeuge 050 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_050
            title: Terminaux Maubeuge 050
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_050
            title: Maubeuge 050 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_050
            title: Maubeuge 050 - Répartition des Terminaux
            classes:

