details:
  page_title: Magasin N°052 - Metz
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_052
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_052
            title: Metz 052 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_052
            title: Metz 052 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_052
            title: Terminaux Metz 052
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_052
            title: Metz 052 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_052
            title: Metz 052 - Répartition des Terminaux
            classes:

