details:
  page_title: Magasin N°053 - Nantes
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_053
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_053
            title: Nantes 053 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_053
            title: Nantes 053 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_053
            title: Terminaux Nantes 053
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_053
            title: Nantes 053 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_053
            title: Nantes 053 - Répartition des Terminaux
            classes:

