details:
  page_title: Magasin N°055 - Beaubourg
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_055
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_055
            title: Beaubourg 055 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_055
            title: Beaubourg 055 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_055
            title: Terminaux Beaubourg 055
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_055
            title: Beaubourg 055 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_055
            title: Beaubourg 055 - Répartition des Terminaux
            classes:

