details:
  page_title: Magasin N°056 - Nancy nord
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_056
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_056
            title: Nancy nord 056 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_056
            title: Nancy nord 056 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_056
            title: Terminaux Nancy nord 056
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_056
            title: Nancy nord 056 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_056
            title: Nancy nord 056 - Répartition des Terminaux
            classes:

