details:
  page_title: Magasin N°059 - Tours nord
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_059
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_059
            title: Tours nord 059 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_059
            title: Tours nord 059 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_059
            title: Terminaux Tours nord 059
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_059
            title: Tours nord 059 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_059
            title: Tours nord 059 - Répartition des Terminaux
            classes:

