details:
  page_title: Magasin N°060 - Caen
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_060
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_060
            title: Caen 060 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_060
            title: Caen 060 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_060
            title: Terminaux Caen 060
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_060
            title: Caen 060 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_060
            title: Caen 060 - Répartition des Terminaux
            classes:

