details:
  page_title: Magasin N°061 - Martigues
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_061
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_061
            title: Martigues 061 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_061
            title: Martigues 061 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_061
            title: Terminaux Martigues 061
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_061
            title: Martigues 061 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_061
            title: Martigues 061 - Répartition des Terminaux
            classes:

