details:
  page_title: Magasin N°063 - Rosny
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_063
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_063
            title: Rosny 063 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_063
            title: Rosny 063 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_063
            title: Terminaux Rosny 063
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_063
            title: Rosny 063 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_063
            title: Rosny 063 - Répartition des Terminaux
            classes:

