details:
  page_title: Magasin N°064 - Rouen tourville
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_064
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_064
            title: Rouen tourville 064 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_064
            title: Rouen tourville 064 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_064
            title: Terminaux Rouen tourville 064
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_064
            title: Rouen tourville 064 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_064
            title: Rouen tourville 064 - Répartition des Terminaux
            classes:

