details:
  page_title: Magasin N°066 - Cabries
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_066
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_066
            title: Cabries 066 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_066
            title: Cabries 066 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_066
            title: Terminaux Cabries 066
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_066
            title: Cabries 066 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_066
            title: Cabries 066 - Répartition des Terminaux
            classes:

