details:
  page_title: Magasin N°067 - Rouen isneauville
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_067
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_067
            title: Rouen isneauville 067 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_067
            title: Rouen isneauville 067 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_067
            title: Terminaux Rouen isneauville 067
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_067
            title: Rouen isneauville 067 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_067
            title: Rouen isneauville 067 - Répartition des Terminaux
            classes:

