details:
  page_title: Magasin N°069 - Amiens
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_069
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_069
            title: Amiens 069 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_069
            title: Amiens 069 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_069
            title: Terminaux Amiens 069
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_069
            title: Amiens 069 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_069
            title: Amiens 069 - Répartition des Terminaux
            classes:

