details:
  page_title: Magasin N°071 - Bayonne
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_071
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_071
            title: Bayonne 071 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_071
            title: Bayonne 071 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_071
            title: Terminaux Bayonne 071
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_071
            title: Bayonne 071 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_071
            title: Bayonne 071 - Répartition des Terminaux
            classes:

