details:
  page_title: Magasin N°072 - Gennevilliers
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_072
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_072
            title: Gennevilliers 072 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_072
            title: Gennevilliers 072 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_072
            title: Terminaux Gennevilliers 072
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_072
            title: Gennevilliers 072 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_072
            title: Gennevilliers 072 - Répartition des Terminaux
            classes:

