details:
  page_title: Magasin N°073 - Livry gargan
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_073
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_073
            title: Livry gargan 073 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_073
            title: Livry gargan 073 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_073
            title: Terminaux Livry gargan 073
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_073
            title: Livry gargan 073 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_073
            title: Livry gargan 073 - Répartition des Terminaux
            classes:

