details:
  page_title: Magasin N°074 - Forbach
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_074
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_074
            title: Forbach 074 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_074
            title: Forbach 074 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_074
            title: Terminaux Forbach 074
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_074
            title: Forbach 074 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_074
            title: Forbach 074 - Répartition des Terminaux
            classes:

