details:
  page_title: Magasin N°075 - Belfort
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_075
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_075
            title: Belfort 075 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_075
            title: Belfort 075 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_075
            title: Terminaux Belfort 075
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_075
            title: Belfort 075 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_075
            title: Belfort 075 - Répartition des Terminaux
            classes:

