details:
  page_title: Magasin N°076 - Grand littoral
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_076
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_076
            title: Grand littoral 076 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_076
            title: Grand littoral 076 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_076
            title: Terminaux Grand littoral 076
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_076
            title: Grand littoral 076 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_076
            title: Grand littoral 076 - Répartition des Terminaux
            classes:

