details:
  page_title: Magasin N°077 - Brie comte robert
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_077
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_077
            title: Brie comte robert 077 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_077
            title: Brie comte robert 077 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_077
            title: Terminaux Brie comte robert 077
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_077
            title: Brie comte robert 077 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_077
            title: Brie comte robert 077 - Répartition des Terminaux
            classes:

