details:
  page_title: Magasin N°078 - Compiegne
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_078
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_078
            title: Compiegne 078 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_078
            title: Compiegne 078 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_078
            title: Terminaux Compiegne 078
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_078
            title: Compiegne 078 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_078
            title: Compiegne 078 - Répartition des Terminaux
            classes:

