details:
  page_title: Magasin N°080 - Nimes
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_080
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_080
            title: Nimes 080 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_080
            title: Nimes 080 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_080
            title: Terminaux Nimes 080
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_080
            title: Nimes 080 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_080
            title: Nimes 080 - Répartition des Terminaux
            classes:

