details:
  page_title: Magasin N°081 - Niort
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_081
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_081
            title: Niort 081 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_081
            title: Niort 081 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_081
            title: Terminaux Niort 081
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_081
            title: Niort 081 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_081
            title: Niort 081 - Répartition des Terminaux
            classes:

