details:
  page_title: Magasin N°082 - Haguenau 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_082
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_082
            title: Haguenau 2 082 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_082
            title: Haguenau 2 082 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_082
            title: Terminaux Haguenau 2 082
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_082
            title: Haguenau 2 082 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_082
            title: Haguenau 2 082 - Répartition des Terminaux
            classes:

