details:
  page_title: Magasin N°084 - Tourcoing 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_084
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_084
            title: Tourcoing 2 084 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_084
            title: Tourcoing 2 084 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_084
            title: Terminaux Tourcoing 2 084
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_084
            title: Tourcoing 2 084 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_084
            title: Tourcoing 2 084 - Répartition des Terminaux
            classes:

