details:
  page_title: Magasin N°088 - Albi
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_088
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_088
            title: Albi 088 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_088
            title: Albi 088 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_088
            title: Terminaux Albi 088
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_088
            title: Albi 088 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_088
            title: Albi 088 - Répartition des Terminaux
            classes:

