details:
  page_title: Magasin N°089 - St Ouen 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_089
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_089
            title: St Ouen 2 089 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_089
            title: St Ouen 2 089 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_089
            title: Terminaux St Ouen 2 089
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_089
            title: St Ouen 2 089 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_089
            title: St Ouen 2 089 - Répartition des Terminaux
            classes:

