details:
  page_title: Magasin N°100 - St Etienne Steel
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_100
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_100
            title: St Etienne Steel 100 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_100
            title: St Etienne Steel 100 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_100
            title: Terminaux St Etienne Steel 100
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_100
            title: St Etienne Steel 100 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_100
            title: St Etienne Steel 100 - Répartition des Terminaux
            classes:

