details:
  page_title: Magasin N°110 - Toulouse
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_110
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_110
            title: Toulouse 110 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_110
            title: Toulouse 110 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_110
            title: Terminaux Toulouse 110
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_110
            title: Toulouse 110 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_110
            title: Toulouse 110 - Répartition des Terminaux
            classes:

