details:
  page_title: Magasin N°111 - Colomiers
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_111
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_111
            title: Colomiers 111 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_111
            title: Colomiers 111 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_111
            title: Terminaux Colomiers 111
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_111
            title: Colomiers 111 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_111
            title: Colomiers 111 - Répartition des Terminaux
            classes:

