details:
  page_title: Magasin N°112 - Châteauroux
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_112
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_112
            title: Châteauroux 112 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_112
            title: Châteauroux 112 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_112
            title: Terminaux Châteauroux 112
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_112
            title: Châteauroux 112 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_112
            title: Châteauroux 112 - Répartition des Terminaux
            classes:

