details:
  page_title: Magasin N°114 - St ouen
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_114
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_114
            title: St ouen 114 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_114
            title: St ouen 114 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_114
            title: Terminaux St ouen 114
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_114
            title: St ouen 114 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_114
            title: St ouen 114 - Répartition des Terminaux
            classes:

