details:
  page_title: Magasin N°115 - St denis
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_115
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_115
            title: St denis 115 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_115
            title: St denis 115 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_115
            title: Terminaux St denis 115
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_115
            title: St denis 115 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_115
            title: St denis 115 - Répartition des Terminaux
            classes:

