details:
  page_title: Magasin N°116 - Collegien
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_116
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_116
            title: Collegien 116 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_116
            title: Collegien 116 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_116
            title: Terminaux Collegien 116
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_116
            title: Collegien 116 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_116
            title: Collegien 116 - Répartition des Terminaux
            classes:

