details:
  page_title: Magasin N°117 - Tassin
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_117
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_117
            title: Tassin 117 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_117
            title: Tassin 117 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_117
            title: Terminaux Tassin 117
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_117
            title: Tassin 117 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_117
            title: Tassin 117 - Répartition des Terminaux
            classes:

