details:
  page_title: Magasin N°119 - La valentine
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_119
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_119
            title: La valentine 119 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_119
            title: La valentine 119 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_119
            title: Terminaux La valentine 119
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_119
            title: La valentine 119 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_119
            title: La valentine 119 - Répartition des Terminaux
            classes:

