details:
  page_title: Magasin N°130 - Nancy sud
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_130
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_130
            title: Nancy sud 130 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_130
            title: Nancy sud 130 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_130
            title: Terminaux Nancy sud 130
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_130
            title: Nancy sud 130 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_130
            title: Nancy sud 130 - Répartition des Terminaux
            classes:

