details:
  page_title: Magasin N°131 - Vendenheim
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_131
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_131
            title: Vendenheim 131 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_131
            title: Vendenheim 131 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_131
            title: Terminaux Vendenheim 131
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_131
            title: Vendenheim 131 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_131
            title: Vendenheim 131 - Répartition des Terminaux
            classes:

