details:
  page_title: Magasin N°132 - Haguenau
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_132
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_132
            title: Haguenau 132 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_132
            title: Haguenau 132 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_132
            title: Terminaux Haguenau 132
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_132
            title: Haguenau 132 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_132
            title: Haguenau 132 - Répartition des Terminaux
            classes:

