details:
  page_title: Magasin N°133 - Clermont-ferrand
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_133
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_133
            title: Clermont-ferrand 133 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_133
            title: Clermont-ferrand 133 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_133
            title: Terminaux Clermont-ferrand 133
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_133
            title: Clermont-ferrand 133 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_133
            title: Clermont-ferrand 133 - Répartition des Terminaux
            classes:

