details:
  page_title: Magasin N°135 - Macon
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_135
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_135
            title: Macon 135 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_135
            title: Macon 135 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_135
            title: Terminaux Macon 135
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_135
            title: Macon 135 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_135
            title: Macon 135 - Répartition des Terminaux
            classes:

