details:
  page_title: Magasin N°136 - PFU Gennevilliers
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_136
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_136
            title: PFU Gennevilliers 136 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_136
            title: PFU Gennevilliers 136 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_136
            title: Terminaux PFU Gennevilliers 136
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_136
            title: PFU Gennevilliers 136 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_136
            title: PFU Gennevilliers 136 - Répartition des Terminaux
            classes:

