details:
  page_title: Magasin N°137 - Vallauris
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_137
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_137
            title: Vallauris 137 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_137
            title: Vallauris 137 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_137
            title: Terminaux Vallauris 137
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_137
            title: Vallauris 137 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_137
            title: Vallauris 137 - Répartition des Terminaux
            classes:

