details:
  page_title: Magasin N°139 - La rochelle 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_139
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_139
            title: La rochelle 2 139 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_139
            title: La rochelle 2 139 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_139
            title: Terminaux La rochelle 2 139
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_139
            title: La rochelle 2 139 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_139
            title: La rochelle 2 139 - Répartition des Terminaux
            classes:

