details:
  page_title: Magasin N°140 - Aubagne 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_140
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_140
            title: Aubagne 2 140 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_140
            title: Aubagne 2 140 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_140
            title: Terminaux Aubagne 2 140
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_140
            title: Aubagne 2 140 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_140
            title: Aubagne 2 140 - Répartition des Terminaux
            classes:

