details:
  page_title: Magasin N°143 - Bois d'arcy
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_143
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_143
            title: Bois d'arcy 143 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_143
            title: Bois d'arcy 143 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_143
            title: Terminaux Bois d'arcy 143
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_143
            title: Bois d'arcy 143 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_143
            title: Bois d'arcy 143 - Répartition des Terminaux
            classes:

