details:
  page_title: Magasin N°144 - Reims nord
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_144
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_144
            title: Reims nord 144 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_144
            title: Reims nord 144 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_144
            title: Terminaux Reims nord 144
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_144
            title: Reims nord 144 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_144
            title: Reims nord 144 - Répartition des Terminaux
            classes:

