details:
  page_title: Magasin N°145 - Metz technopole
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_145
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_145
            title: Metz technopole 145 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_145
            title: Metz technopole 145 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_145
            title: Terminaux Metz technopole 145
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_145
            title: Metz technopole 145 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_145
            title: Metz technopole 145 - Répartition des Terminaux
            classes:

