details:
  page_title: Magasin N°146 - Vannes
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_146
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_146
            title: Vannes 146 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_146
            title: Vannes 146 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_146
            title: Terminaux Vannes 146
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_146
            title: Vannes 146 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_146
            title: Vannes 146 - Répartition des Terminaux
            classes:

