details:
  page_title: Magasin N°147 - Rennes nord
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_147
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_147
            title: Rennes nord 147 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_147
            title: Rennes nord 147 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_147
            title: Terminaux Rennes nord 147
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_147
            title: Rennes nord 147 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_147
            title: Rennes nord 147 - Répartition des Terminaux
            classes:

