details:
  page_title: Magasin N°148 - Dreux
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_148
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_148
            title: Dreux 148 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_148
            title: Dreux 148 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_148
            title: Terminaux Dreux 148
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_148
            title: Dreux 148 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_148
            title: Dreux 148 - Répartition des Terminaux
            classes:

