details:
  page_title: Magasin N°151 - Bouliac
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_151
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_151
            title: Bouliac 151 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_151
            title: Bouliac 151 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_151
            title: Terminaux Bouliac 151
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_151
            title: Bouliac 151 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_151
            title: Bouliac 151 - Répartition des Terminaux
            classes:

