details:
  page_title: Magasin N°152 - St chamond
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_152
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_152
            title: St chamond 152 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_152
            title: St chamond 152 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_152
            title: Terminaux St chamond 152
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_152
            title: St chamond 152 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_152
            title: St chamond 152 - Répartition des Terminaux
            classes:

