details:
  page_title: Magasin N°153 - St aunes
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_153
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_153
            title: St aunes 153 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_153
            title: St aunes 153 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_153
            title: Terminaux St aunes 153
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_153
            title: St aunes 153 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_153
            title: St aunes 153 - Répartition des Terminaux
            classes:

