details:
  page_title: Magasin N°154 - Annemasse
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_154
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_154
            title: Annemasse 154 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_154
            title: Annemasse 154 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_154
            title: Terminaux Annemasse 154
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_154
            title: Annemasse 154 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_154
            title: Annemasse 154 - Répartition des Terminaux
            classes:

