details:
  page_title: Magasin N°155 - Perigueux
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_155
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_155
            title: Perigueux 155 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_155
            title: Perigueux 155 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_155
            title: Terminaux Perigueux 155
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_155
            title: Perigueux 155 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_155
            title: Perigueux 155 - Répartition des Terminaux
            classes:

