details:
  page_title: Magasin N°156 - Gradignan
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_156
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_156
            title: Gradignan 156 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_156
            title: Gradignan 156 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_156
            title: Terminaux Gradignan 156
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_156
            title: Gradignan 156 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_156
            title: Gradignan 156 - Répartition des Terminaux
            classes:

