details:
  page_title: Magasin N°157 - Mulhouse
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_157
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_157
            title: Mulhouse 157 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_157
            title: Mulhouse 157 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_157
            title: Terminaux Mulhouse 157
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_157
            title: Mulhouse 157 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_157
            title: Mulhouse 157 - Répartition des Terminaux
            classes:

