details:
  page_title: Magasin N°158 - Rivesaltes
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_158
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_158
            title: Rivesaltes 158 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_158
            title: Rivesaltes 158 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_158
            title: Terminaux Rivesaltes 158
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_158
            title: Rivesaltes 158 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_158
            title: Rivesaltes 158 - Répartition des Terminaux
            classes:

