details:
  page_title: Magasin N°159 - Calais 3
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_159
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_159
            title: Calais 3 159 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_159
            title: Calais 3 159 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_159
            title: Terminaux Calais 3 159
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_159
            title: Calais 3 159 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_159
            title: Calais 3 159 - Répartition des Terminaux
            classes:

