details:
  page_title: Magasin N°160 - La roche sur yon
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_160
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_160
            title: La roche sur yon 160 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_160
            title: La roche sur yon 160 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_160
            title: Terminaux La roche sur yon 160
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_160
            title: La roche sur yon 160 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_160
            title: La roche sur yon 160 - Répartition des Terminaux
            classes:

