details:
  page_title: Magasin N°161 - Rueil-malmaison
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_161
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_161
            title: Rueil-malmaison 161 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_161
            title: Rueil-malmaison 161 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_161
            title: Terminaux Rueil-malmaison 161
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_161
            title: Rueil-malmaison 161 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_161
            title: Rueil-malmaison 161 - Répartition des Terminaux
            classes:

