details:
  page_title: Magasin N°162 - Besancon
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_162
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_162
            title: Besancon 162 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_162
            title: Besancon 162 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_162
            title: Terminaux Besancon 162
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_162
            title: Besancon 162 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_162
            title: Besancon 162 - Répartition des Terminaux
            classes:

