details:
  page_title: Magasin N°165 - Angouleme
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_165
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_165
            title: Angouleme 165 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_165
            title: Angouleme 165 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_165
            title: Terminaux Angouleme 165
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_165
            title: Angouleme 165 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_165
            title: Angouleme 165 - Répartition des Terminaux
            classes:

