details:
  page_title: Magasin N°166 - Valence
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_166
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_166
            title: Valence 166 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_166
            title: Valence 166 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_166
            title: Terminaux Valence 166
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_166
            title: Valence 166 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_166
            title: Valence 166 - Répartition des Terminaux
            classes:

