details:
  page_title: Magasin N°167 - Thoiry
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_167
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_167
            title: Thoiry 167 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_167
            title: Thoiry 167 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_167
            title: Terminaux Thoiry 167
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_167
            title: Thoiry 167 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_167
            title: Thoiry 167 - Répartition des Terminaux
            classes:

