details:
  page_title: Magasin N°168 - St etienne 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_168
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_168
            title: St etienne 2 168 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_168
            title: St etienne 2 168 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_168
            title: Terminaux St etienne 2 168
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_168
            title: St etienne 2 168 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_168
            title: St etienne 2 168 - Répartition des Terminaux
            classes:

