details:
  page_title: Magasin N°169 - Vourles
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_169
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_169
            title: Vourles 169 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_169
            title: Vourles 169 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_169
            title: Terminaux Vourles 169
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_169
            title: Vourles 169 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_169
            title: Vourles 169 - Répartition des Terminaux
            classes:

