details:
  page_title: Magasin N°171 - Perpignan 3
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_171
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_171
            title: Perpignan 3 171 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_171
            title: Perpignan 3 171 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_171
            title: Terminaux Perpignan 3 171
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_171
            title: Perpignan 3 171 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_171
            title: Perpignan 3 171 - Répartition des Terminaux
            classes:

