details:
  page_title: Magasin N°173 - Biganos
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_173
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_173
            title: Biganos 173 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_173
            title: Biganos 173 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_173
            title: Terminaux Biganos 173
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_173
            title: Biganos 173 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_173
            title: Biganos 173 - Répartition des Terminaux
            classes:

