details:
  page_title: Magasin N°174 - Cholet
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_174
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_174
            title: Cholet 174 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_174
            title: Cholet 174 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_174
            title: Terminaux Cholet 174
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_174
            title: Cholet 174 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_174
            title: Cholet 174 - Répartition des Terminaux
            classes:

