details:
  page_title: Magasin N°175 - Brive la gaillarde
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_175
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_175
            title: Brive la gaillarde 175 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_175
            title: Brive la gaillarde 175 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_175
            title: Terminaux Brive la gaillarde 175
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_175
            title: Brive la gaillarde 175 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_175
            title: Brive la gaillarde 175 - Répartition des Terminaux
            classes:

