details:
  page_title: Magasin N°176 - Agen
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_176
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_176
            title: Agen 176 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_176
            title: Agen 176 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_176
            title: Terminaux Agen 176
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_176
            title: Agen 176 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_176
            title: Agen 176 - Répartition des Terminaux
            classes:

