details:
  page_title: Magasin N°177 - Annecy
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_177
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_177
            title: Annecy 177 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_177
            title: Annecy 177 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_177
            title: Terminaux Annecy 177
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_177
            title: Annecy 177 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_177
            title: Annecy 177 - Répartition des Terminaux
            classes:

