details:
  page_title: Magasin N°179 - Cherbourg
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_179
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_179
            title: Cherbourg 179 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_179
            title: Cherbourg 179 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_179
            title: Terminaux Cherbourg 179
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_179
            title: Cherbourg 179 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_179
            title: Cherbourg 179 - Répartition des Terminaux
            classes:

