details:
  page_title: Magasin N°180 - Nanterre
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_180
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_180
            title: Nanterre 180 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_180
            title: Nanterre 180 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_180
            title: Terminaux Nanterre 180
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_180
            title: Nanterre 180 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_180
            title: Nanterre 180 - Répartition des Terminaux
            classes:

