details:
  page_title: Magasin N°181 - Quimper
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_181
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_181
            title: Quimper 181 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_181
            title: Quimper 181 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_181
            title: Terminaux Quimper 181
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_181
            title: Quimper 181 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_181
            title: Quimper 181 - Répartition des Terminaux
            classes:

