details:
  page_title: Magasin N°182 - Paris Daumesnil
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_182
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_182
            title: Paris Daumesnil 182 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_182
            title: Paris Daumesnil 182 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_182
            title: Terminaux Paris Daumesnil 182
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_182
            title: Paris Daumesnil 182 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_182
            title: Paris Daumesnil 182 - Répartition des Terminaux
            classes:

