details:
  page_title: Magasin N°183 - Douai 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_183
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_183
            title: Douai 2 183 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_183
            title: Douai 2 183 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_183
            title: Terminaux Douai 2 183
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_183
            title: Douai 2 183 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_183
            title: Douai 2 183 - Répartition des Terminaux
            classes:

