details:
  page_title: Magasin N°184 - Le havre 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_184
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_184
            title: Le havre 2 184 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_184
            title: Le havre 2 184 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_184
            title: Terminaux Le havre 2 184
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_184
            title: Le havre 2 184 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_184
            title: Le havre 2 184 - Répartition des Terminaux
            classes:

