details:
  page_title: Magasin N°185 - Meaux
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_185
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_185
            title: Meaux 185 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_185
            title: Meaux 185 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_185
            title: Terminaux Meaux 185
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_185
            title: Meaux 185 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_185
            title: Meaux 185 - Répartition des Terminaux
            classes:

