details:
  page_title: Magasin N°186 - Reims2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_186
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_186
            title: Reims2 186 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_186
            title: Reims2 186 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_186
            title: Terminaux Reims2 186
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_186
            title: Reims2 186 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_186
            title: Reims2 186 - Répartition des Terminaux
            classes:

