details:
  page_title: Magasin N°187 - Blois
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_187
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_187
            title: Blois 187 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_187
            title: Blois 187 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_187
            title: Terminaux Blois 187
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_187
            title: Blois 187 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_187
            title: Blois 187 - Répartition des Terminaux
            classes:

