details:
  page_title: Magasin N°188 - Mantes 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_188
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_188
            title: Mantes 2 188 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_188
            title: Mantes 2 188 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_188
            title: Terminaux Mantes 2 188
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_188
            title: Mantes 2 188 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_188
            title: Mantes 2 188 - Répartition des Terminaux
            classes:

