details:
  page_title: Magasin N°189 - Montauban
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_189
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_189
            title: Montauban 189 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_189
            title: Montauban 189 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_189
            title: Terminaux Montauban 189
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_189
            title: Montauban 189 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_189
            title: Montauban 189 - Répartition des Terminaux
            classes:

