details:
  page_title: Magasin N°190 - Paris 19
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_190
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_190
            title: Paris 19 190 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_190
            title: Paris 19 190 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_190
            title: Terminaux Paris 19 190
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_190
            title: Paris 19 190 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_190
            title: Paris 19 190 - Répartition des Terminaux
            classes:

