details:
  page_title: Magasin N°191 - Beauvais
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_191
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_191
            title: Beauvais 191 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_191
            title: Beauvais 191 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_191
            title: Terminaux Beauvais 191
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_191
            title: Beauvais 191 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_191
            title: Beauvais 191 - Répartition des Terminaux
            classes:

