details:
  page_title: Magasin N°192 - Fréjus
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_192
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_192
            title: Fréjus 192 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_192
            title: Fréjus 192 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_192
            title: Terminaux Fréjus 192
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_192
            title: Fréjus 192 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_192
            title: Fréjus 192 - Répartition des Terminaux
            classes:

