details:
  page_title: Magasin N°193 - Brest
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_193
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_193
            title: Brest 193 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_193
            title: Brest 193 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_193
            title: Terminaux Brest 193
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_193
            title: Brest 193 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_193
            title: Brest 193 - Répartition des Terminaux
            classes:

