details:
  page_title: Magasin N°194 - Grenoble 2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_194
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_194
            title: Grenoble 2 194 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_194
            title: Grenoble 2 194 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_194
            title: Terminaux Grenoble 2 194
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_194
            title: Grenoble 2 194 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_194
            title: Grenoble 2 194 - Répartition des Terminaux
            classes:

