details:
  page_title: Magasin N°195 - Avignon
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_195
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_195
            title: Avignon 195 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_195
            title: Avignon 195 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_195
            title: Terminaux Avignon 195
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_195
            title: Avignon 195 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_195
            title: Avignon 195 - Répartition des Terminaux
            classes:

