details:
  page_title: Magasin N°196 - Paris La Madeleine
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_196
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_196
            title: Paris La Madeleine 196 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_196
            title: Paris La Madeleine 196 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_196
            title: Terminaux Paris La Madeleine 196
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_196
            title: Paris La Madeleine 196 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_196
            title: Paris La Madeleine 196 - Répartition des Terminaux
            classes:

