details:
  page_title: Magasin N°199 - La vigie2
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_199
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_199
            title: La vigie2 199 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_199
            title: La vigie2 199 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_199
            title: Terminaux La vigie2 199
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_199
            title: La vigie2 199 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_199
            title: La vigie2 199 - Répartition des Terminaux
            classes:

