details:
  page_title: Magasin N°205 - Batignolles
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_205
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_205
            title: Batignolles 205 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_205
            title: Batignolles 205 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_205
            title: Terminaux Batignolles 205
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_205
            title: Batignolles 205 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_205
            title: Batignolles 205 - Répartition des Terminaux
            classes:

