details:
  page_title: Magasin N°292 - St louis
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_292
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_292
            title: St louis 292 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_292
            title: St louis 292 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_292
            title: Terminaux St louis 292
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_292
            title: St louis 292 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_292
            title: St louis 292 - Répartition des Terminaux
            classes:

