details:
  page_title: Magasin N°293 - Ajaccio
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_293
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_293
            title: Ajaccio 293 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_293
            title: Ajaccio 293 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_293
            title: Terminaux Ajaccio 293
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_293
            title: Ajaccio 293 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_293
            title: Ajaccio 293 - Répartition des Terminaux
            classes:

