details:
  page_title: Magasin N°294 - Limoges
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_294
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_294
            title: Limoges 294 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_294
            title: Limoges 294 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_294
            title: Terminaux Limoges 294
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_294
            title: Limoges 294 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_294
            title: Limoges 294 - Répartition des Terminaux
            classes:

