details:
  page_title: Magasin N°295 - La reunion
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_295
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_295
            title: La reunion 295 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_295
            title: La reunion 295 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_295
            title: Terminaux La reunion 295
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_295
            title: La reunion 295 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_295
            title: La reunion 295 - Répartition des Terminaux
            classes:

