details:
  page_title: Magasin N°297 - Guerande
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_297
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_297
            title: Guerande 297 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_297
            title: Guerande 297 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_297
            title: Terminaux Guerande 297
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_297
            title: Guerande 297 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_297
            title: Guerande 297 - Répartition des Terminaux
            classes:

