details:
  page_title: Magasin N°298 - Bastia
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_298
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_298
            title: Bastia 298 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_298
            title: Bastia 298 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_298
            title: Terminaux Bastia 298
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_298
            title: Bastia 298 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_298
            title: Bastia 298 - Répartition des Terminaux
            classes:

