details:
  page_title: Magasin N°607 - Chateauneuf-sur-Loire
layout:
  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_bydevices_607
            title: Nombre de Terminaux
            classes:


      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_shop_607
            title: Chateauneuf-sur-Loire 607 - Terminaux OnLine / Offline
            classes:

      - col_1_of_2 :
          - tile_template: half_doughnut_chart
            tile_id: hd_devise_used_607
            title: Chateauneuf-sur-Loire 607 - Nombre de Terminal Utilisé
            classes:


  - row_1_of_2 :
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_607
            title: Terminaux Chateauneuf-sur-Loire 607
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_network_607
            title: Chateauneuf-sur-Loire 607 - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_shops_used_607
            title: Chateauneuf-sur-Loire 607 - Répartition des Terminaux
            classes:

