details:
    page_tile: Magasin N°XXX - NNNNNNNN
layout:
    - row_1_of_2:
        - col_1_of_2:
            - tile_template: just_value
              tile_id: jv_alldevices
              title: Entrepots - Nombre de terminaux
              classes:

        - col_1_of_2:
            - tile_template: pie_chart
              tile_id: pie_chart_online
              title: Entrepots - Terminaux OnLine / Offline
              classes:

        - col_1_of_2 :
            - tile_template: just_value
              tile_id: jv_whs_scans
              title: Entrepots - Nombre de scans Total
              classes:
                
    - row_1_of_2 :
        - col_1_of_2 flip-time-6:
            - tile_template: big_value
              tile_id: bv_shops_bydevices_XXX
              title: Magasin XXX - Nombre de Terminaux
              classes:

            - tile_template: big_value
              tile_id: bv_shops_XXX
              title: Terminaux Magasin XXX
              classes:

        - col_1_of_2 flip-time-6:
            - tile_template: pie_chart
              tile_id: pie_chart_online_shop_XXX
              title: Magasin XXX - Terminaux OnLine / Offline
              classes:

            - tile_template: big_value
              tile_id: bv_shops_network_XXX
              title: Terminaux Magasin XXX
              classes:
                -
        - col_1_of_2 flip-time-6:
            - tile_template: pie_chart
              tile_id: pie_chart_devise_used_XXX
              title: Magasins XXX - Nombre de Terminal Utilisé
              classes:

            - tile_template: big_value
              tile_id: bv_shops_used_XXX
              title: Terminaux Magasin XXX
              classes:

