details:
  page_title: Entrepôt N°XXX - NNNNNNNN
layout:
  - row_1_of_2:
      - col_1_of_2 flip-time-6:
          - tile_template: big_value
            tile_id: bv_wh_bydevices_XXX
            title: Nombre de terminaux
            classes:

          - tile_template: just_value
            tile_id: jv_whs_scans_XXX
            title: Nombre de scans Total
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_online_wh_XXX
            title: NNNNNNNN XXX - Terminaux OnLine / Offline
            classes:

      - col_1_of_2:
          - tile_template: half_doughnut_chart
            tile_id: hd_wh_device_used_XXX
            title: NNNNNNNN XXX - Nombre de Terminal Utilisé
            classes:

  - row_1_of_2:
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_XXX
            title: Terminaux NNNNNNNN XXX
            classes:

      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_network_XXX
            title: NNNNNNNN XXX - Répartition des terminaux
            classes:
              -
      - col_1_of_2:
          - tile_template: big_value
            tile_id: bv_wh_used_XXX
            title: NNNNNNNN XXX - Répartition des Terminaux
            classes:
