details:
    page_tile: Warehouse N°XXX - Lezennes City
layout:
    - row_1_of_2:
        - col_1_of_2:
            - tile_template: just_value
              tile_id: jv_alldevices
              title: Nombre de terminaux
              classes:

        - col_1_of_2:
            - tile_template: pie_chart
              tile_id: pie_chart_online
              title: Terminaux OnLine / Offline
              classes:

        - col_1_of_2:
            - tile_template: pie_chart
              tile_id: pie_model_warehouse
              title: Répartition des Models de Terminaux
              classes:

    - row_1_of_2:
        - col_1_of_2:
            - tile_template: doughnut_chart
              tile_id: doug_devices_by_warehouse
              title: Nombre de terminaux par entrepot
              classes:

        - col_1_of_2 :
            - tile_template: just_value
              tile_id: jv_whs_scans
              title: Nombre de scans Total
              classes:


